version: '3'

##       Docker Networks Configuration      ##
networks:
  trusted-zone:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24
  DMZ:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/24
  zone-woodytoys:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.2.0.0/24

##       Docker Services Configuration      ##
services:
  web-serveur:
    build:
      context: ./DMZ/web
      dockerfile: Dockerfile
    hostname: www
    domainname: woodytoys.be
    ports:
      - 80:80
      - 8080:8080
    links:
      - database
    container_name: web-serveur
    volumes:
      - ./DMZ/web/php/src:/var/www/html/

  soa-externe:
    image: ubuntu/bind9
    networks:
      DMZ:
        ipv4_address: 172.16.0.3
    container_name: soa-externe

  mail-serveur:
    image: ubuntu
    networks:
      DMZ:
        ipv4_address: 172.16.0.4
    container_name: mail-serveur

  soa-interne:
    build:
      context: ./trusted-zone/SOA-interne
      dockerfile: Dockerfile
    networks:
      trusted-zone:
        ipv4_address: 10.0.0.2
    container_name: soa-interne
  
  resolver:
    build:
      context: ./trusted-zone/resolveur
      dockerfile: Dockerfile
    networks:
      trusted-zone:
        ipv4_address: 10.0.0.3
    container_name: resolver
  
  database:
    image: mysql
    build:
      context: ./trusted-zone/db
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE : woodytoys_db
      MYSQL_ROOT_PASSWORD: 'admin'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
    restart: always
    container_name: database
    volumes:
      - ./trusted-zone/db:/docker-entrypoint-initdb.d

  employe1:
    build:
      context: ./woodytoys-zone/Employes
      dockerfile: Dockerfile
    networks:
      trusted-zone:
        ipv4_address: 10.0.0.5
    container_name: employe1

  employe2:
    build:
      context: ./woodytoys-zone/Employes
      dockerfile: Dockerfile
    networks:
      DMZ:
        ipv4_address: 172.16.0.5
    container_name: employe2
