version: '3'

##       Docker Networks Configuration      ##

networks:
  trusted-zone:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24

  woodytoys-zone:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/24

  database-zone:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.2.0.0/24
        
  dmz:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.3.0.0/24

##       Docker Services Configuration      ##

services:

  ##       Trusted zone services      ##
  soa-interne:
    build:
      context: ./trusted-zone/soa-interne
      dockerfile: Dockerfile
    networks:
      trusted-zone:
        ipv4_address: 10.0.0.2
    container_name: soa-interne
  
  resolver:
    build:
      context: ./trusted-zone/resolveur
      dockerfile: Dockerfile
    networks:
      trusted-zone:
        ipv4_address: 10.0.0.3
    container_name: resolver

  web-interne:
    build:
      context: ./trusted-zone/web-interne
      dockerfile: Dockerfile
    hostname: www
    domainname: woodytoys.be
    ports:
      - 80:80
      - 8080:8080
    networks:
      trusted-zone:
        ipv4_address: 10.0.0.4
    links:
      - database
    container_name: web-interne
    volumes:
      - ./trusted-zone/web-interne/php/src:/var/www/html/

  ##          Woodytoys zone services         ##
  employe1:
    build:
      context: ./woodytoys-zone/Employes
      dockerfile: Dockerfile
    networks:
      woodytoys-zone:
        ipv4_address: 10.1.0.2
    container_name: employe1

  employe2:
    build:
      context: ./woodytoys-zone/Employes
      dockerfile: Dockerfile
    networks:
      woodytoys-zone:
        ipv4_address: 10.1.0.3
    container_name: employe2

  ##          Database zone services         ##
  database:
    image: mysql
    build:
      context: ./database-zone/db
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    networks:
      database-zone:
        ipv4_address: 10.2.0.2
    environment:
      MYSQL_DATABASE : woodytoys_db
      MYSQL_ROOT_PASSWORD: 'admin'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
    container_name: database
    volumes:
      - ./database-zone/db:/docker-entrypoint-initdb.d

  ##          Dmz services         ##
  web-externe:
    image: php:8.0-apache
    networks:
      dmz:
        ipv4_address: 10.3.0.2
    container_name: web-externe

  soa-externe:
    build:
      context: ./dmz/soa-externe
      dockerfile: Dockerfile
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    networks:
      dmz:
        ipv4_address: 10.3.0.3
    container_name: soa-externe

  mail-serveur:
    build:
      context: ./dmz/mail
      dockerfile: Dockerfile
    networks:
      dmz:
        ipv4_address: 10.3.0.4
    container_name: mail-server
    hostname: localhost

  contact:
    build:
      context: ./dmz/mail/Client-mail
      dockerfile: Dockerfile
    networks:
      dmz:
        ipv4_address: 10.3.0.5
    tty: true

  b2b:
    build:
      context: ./dmz/mail/Client-b2b
      dockerfile: Dockerfile
    networks:
      dmz:
        ipv4_address: 10.3.0.6
    tty: true

  postfix:
    build:
      context: ./dmz/mail/smtp
      dockerfile: Dockerfile
    networks:
      dmz:
        ipv4_address: 10.3.0.7
    hostname: localhost

  pop-imap:
    build:
      context: ./dmz/mail/dovecot
      dockerfile: Dockerfile
    ports:
      - 110:110
      - 143:143 
    networks:
      dmz:
        ipv4_address: 10.3.0.8
