version: '3'

##       Docker Networks Configuration      ##

networks:
  trusted-zone:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24

  woodytoys-zone:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/24

  database-zone:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.2.0.0/24
        
  dmz:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.3.0.0/24

##       Docker Services Configuration      ##

services:

  ##       Trusted zone services      ##
  soa-interne:
    build:
      context: ./trusted-zone/SOA-interne
      dockerfile: Dockerfile
    ports:
      []
    networks:
      trusted-zone:
        ipv4_address: 10.0.0.2
    container_name: soa-interne

  resolver:
    build:
      context: ./trusted-zone/resolveur
      dockerfile: Dockerfile
    ports:
      []
    networks:
      trusted-zone:
        ipv4_address: 10.0.0.3
    container_name: resolver

  web-interne:
    build:
      context: ./trusted-zone/web-interne
      dockerfile: Dockerfile
    hostname: www
    domainname: woodytoys.be
    ports:
      - 81:80
    networks:
      database-zone:
        ipv4_address: 10.2.0.3
      trusted-zone:
        ipv4_address: 10.0.0.4
    links:
      - database
    container_name: web-interne
    volumes:
      - ./trusted-zone/web-interne/php/src:/var/www/html/

  ##          Woodytoys zone services         ##
  employe1:
    build:
      context: ./woodytoys-zone/Employes
      dockerfile: Dockerfile
    networks:
      dmz:
        ipv4_address: 10.3.0.10
      woodytoys-zone:
        ipv4_address: 10.1.0.2
    container_name: employe1

  employe2:
    build:
      context: ./woodytoys-zone/Employes
      dockerfile: Dockerfile
    networks:
      trusted-zone:
        ipv4_address: 10.0.0.5
      woodytoys-zone:
        ipv4_address: 10.1.0.3
    tty: true
    container_name: contact

  ##          Database zone services         ##
  database:
    image: mysql
    build:
      context: ./database-zone/db
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    networks:
      dmz: 
        ipv4_address: 10.3.0.9
      database-zone:
        ipv4_address: 10.2.0.2
    environment:
      MYSQL_DATABASE : woodytoys_db
      MYSQL_ROOT_PASSWORD: 'admin'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      #MYSQL_DATABASE : ${MYSQL_DATABASE}
      #MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      #MYSQL_USER: ${MYSQL_USER}
      #MYSQL_PASSWORD: ${MYSQL_DATABASE}
    container_name: database
    volumes:
      - ./database-zone/db:/data/db

  ##          Dmz services         ##

  web-externe:
    build:
      context: ./DMZ/web-externe
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    networks:
      dmz:
        ipv4_address: 10.3.0.2
    links:
      - database
    container_name: web-externe

  soa-externe:
    build:
      context: ./DMZ/soa-externe
      dockerfile: Dockerfile
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    networks:
      dmz:
        ipv4_address: 10.3.0.3
    container_name: soa-externe

  mail-serveur:
    build:
      context: ./DMZ/mail
      dockerfile: Dockerfile
    networks:
      dmz:
        ipv4_address: 10.3.0.4
    container_name: mail-server
    hostname: localhost

  contact:
    build:
      context: ./DMZ/mail/Client-mail
      dockerfile: Dockerfile
    networks:
      dmz:
        ipv4_address: 10.3.0.5
    tty: true

  b2b:
    build:
      context: ./DMZ/mail/Client-b2b
      dockerfile: Dockerfile
    networks:
      dmz:
        ipv4_address: 10.3.0.6
    tty: true

  postfix:
    build:
      context: ./DMZ/mail/smtp
      dockerfile: Dockerfile
    networks:
      dmz:
        ipv4_address: 10.3.0.7
    hostname: localhost

  pop-imap:
    build:
      context: ./DMZ/mail/dovecot
      dockerfile: Dockerfile
    ports:
      - 110:110
      - 143:143 
    networks:
      dmz:
        ipv4_address: 10.3.0.8

##       Docker Volumes      ##

volumes:
  db:
