FROM ubuntu/bind9
MAINTAINER Julien Claerhout <julienclaerhout@gmail.com>

RUN apt-get update && apt-get install bind9 && apt install dnsutils -y && apt-get install -y iputils-ping
RUN mkdir /var/log/named

COPY named.conf /etc/bind

EXPOSE 53/udp
EXPOSE 53/tcp

CMD ["named", " -g"]
